{% set name = "azure-mgmt-eventhub" %}
{% set version = "12.0.0b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure_mgmt_eventhub-{{ version }}.tar.gz
  sha256: e7bdf166c32de7aef5a626953f536ca4f1c6115f16795354c8c3f38f1da1fe10

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - setuptools
    - wheel
    - python
    - pip
  run:
    - python
    - isodate >=0.6.1
    - typing_extensions >=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.5.0

test:
  imports:
    - azure.mgmt.eventhub
    - azure.mgmt.eventhub.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Event Hub Management Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    This is the Microsoft Azure Event Hub Management Client Library.
  doc_url: https://github.com/Azure/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
